Add select/remove multiple missions
redpelicans/mission-impossible pull request #40
Opened 2018-01-12 00:06 UTC by ale-floc

2018-01-12 00:09 UTC, ale-floc commented
TypeError: Cannot read property 'listen' of undefined

sur les test, on verra sa demain, bonne nuit :P

2018-01-15 16:45 UTC, nicolas-briemant requested changes
almost good.
même remarque qu'à mike: pourquoi supprimer registerServiceWorker ?

2018-01-15 16:45 UTC, nicolas-briemant commented on src/App.js
> +    <Header>
check si tu n'a pas un pb d'indentation (rappel: pas de tab, 2 spaces)

2018-01-15 16:45 UTC, nicolas-briemant commented on src/reducers/index.js
> +      return { ...state, missions: [...removeMissionFromArray(state.missions, action.payload.missionId)] };
pas besoin de copier les items car map et filter font déjà une copie

2018-01-15 17:11 UTC, nicolas-briemant approved these changes

2018-01-15 17:11 UTC, merged